### ISSUE TITLE
Новые релизы bem-core и bem-components

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem-forum-content-ru#1287]
Привет!

Мы, наконец, выпустили новые версии bem-core и bem-components!

### bem-core 4.2.0
Версия полностью обратносовместимая, так что обновление должно быть совершенно «бесплатным».

Главным изменением является совместимость с [bem-xjst 8.x](https://ru.bem.info/platform/bem-xjst/).
Кроме того в версию вошла большая работа по переводу документации на английский и, конечно же, исправления ошибок и мелкие улучшения.
Подробности читайте в [changelog](https://github.com/bem/bem-core/releases/tag/v4.2.0).

### bem-components 5.1.0
Версия также является обратносовместимой и не должна требовать никаких усилий при обновлении.

В ней обновлена зависимость от bem-core до 4.2.0, добавлено визуальное оформление для `link_disabled` и исправлены некоторые ошибки.

Подробности в [changelog](https://github.com/bem/bem-components/releases/tag/v5.1.0).

### bem-components 6.0.0
Эта версия обязательно требует обновления до `bem-xjst 8`, где появились новые полезные режимы и исправлена работа режима extend. Необходимые пакеты для сборки на ENB (`enb-bemxjst 8.6.7`) или gulp (`gulp-bem-xjst 3.0.0`) уже доступны для установки.

При переходе вам может пригодиться автоматический мигратор шаблонов: https://github.com/bem/bem-xjst/tree/master/migration#migration-tool-for-templates

Кроме новых шаблонов версия ничем не отличается от `5.1.0`.

### Где попробовать

Свежие bem-core 4.2.0 и bem-components 6.0.0 уже внедрены в [project-stub](https://github.com/bem/project-stub/).

Если при обновлении у вас возникнут какие-либо проблемы — пишите, мы постараемся помочь.

**Comment by webtehnology** [comment]
Решена ли эта проблема
https://github.com/bem-site/bem-forum-content-ru/issues/1260

**Comment by tadatuta** [comment]
@webtehnology 

> Решена ли эта проблема

Слава @miripiruni бувально час назад влил pull request https://github.com/bem/bem-xjst/pull/424, теперь ждем версию `bem-xjst` и останется протащить апдейт в `gulp-bem-xjst`. Думаю, есть все шансы, что на этой неделе сойдется.

**Comment by skad0** [comment]
Супер!

**Comment by webtehnology** [comment]
@tadatuta  Добрый день!
Вопрос выше решен ли?

**Comment by miripiruni** [comment]
@webtehnology https://github.com/bem/bem-xjst/pull/424 влит, но пока не выпущена версия, так как не было никаких проверок этой функциональности в бою. Можете попробовать собрать что-то свое из ветки master в bem/bem-xjst

**Comment by DjonyBastone** [comment]
**Migration tool for templates**

Миграция выдает лог:

```
$ ./migration/lib/index.js --lint --input ../../common.blocks/*/ --from 7 --to 8
bem-xjst static linter startedâ¦


Check rule: attrs to addattrs


"." ­¥ ï¢«ï¥âáï ¢­ãâà¥­­¥© ¨«¨ ¢­¥è­¥©
ª®¬ ­¤®©, ¨á¯®«­ï¥¬®© ¯à®£à ¬¬®© ¨«¨ ¯ ª¥â­ë¬ ä ©«®¬.
child_process.js:526
    throw err;
    ^

Error: Command failed: ./migration/node_modules/jscodeshift/bin/jscodeshift.sh -t ./migration/lib/transformers/8-attrs-to-addattrs.js ../../common.blocks/breadcrumbs/breadcrumbs.bemhtml.js  --print --lint=true
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at D:\Verstka\bem-bemtree-static\node_modules\bem-xjst\migration\lib\index.js:105:5
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

Использовалась консоль GitBash

**Comment by webtehnology** [comment]
К сожалению даже после полного обновления project-stub и отдельного обновления bem-xjst  выдается ошибка 
Module "block-1": can't resolve dependence "BEMHTML"
