### ISSUE TITLE
npm ERR! Exit status 1

### ISSUE THREAD

**Issue by voron121** [bem-site/bem-forum-content-ru#1319]
Доброго времени суток. Пробую начать работать с БЭМ . Решил приступить с создания собственного проекта по мануалу https://ru.bem.info/platform/tutorials/start-with-project-stub/  . На шаге сборке проекта nmp ругается и пишет  в лог сл: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bem-project-stub@2.0.0~prestart: bem-project-stub@2.0.0
6 silly lifecycle bem-project-stub@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle bem-project-stub@2.0.0~start: bem-project-stub@2.0.0
8 verbose lifecycle bem-project-stub@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle bem-project-stub@2.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\web\OpenServer\domains\droid\main\node_modules\.bin;C:\Users\Vadim\bin;E:\Git\mingw64\bin;E:\Git\usr\local\bin;E:\Git\usr\bin;E:\Git\usr\bin;E:\Git\mingw64\bin;E:\Git\usr\bin;C:\Users\Vadim\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files\PuTTY;E:\Git\cmd;C:\Program Files\nodejs;C:\Users\Vadim\AppData\Local\Microsoft\WindowsApps;C:\Users\Vadim\AppData\Roaming\npm;E:\Git\usr\bin\vendor_perl;E:\Git\usr\bin\core_perl
10 verbose lifecycle bem-project-stub@2.0.0~start: CWD: C:\web\OpenServer\domains\droid\main
11 silly lifecycle bem-project-stub@2.0.0~start: Args: [ '/d /s /c', 'enb server' ]
12 silly lifecycle bem-project-stub@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle bem-project-stub@2.0.0~start: Failed to exec start script
14 verbose stack Error: bem-project-stub@2.0.0 start: `enb server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bem-project-stub@2.0.0
16 verbose cwd C:\web\OpenServer\domains\droid\main
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bem-project-stub@2.0.0 start: `enb server`
22 error Exit status 1
23 error Failed at the bem-project-stub@2.0.0 start script 'enb server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bem-project-stub package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     enb server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bem-project-stub
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bem-project-stub
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Версия 4 +. Подскажите плз в чем трабла. Где я делаю не так ?

**Comment by tadatuta** [comment]
По логу видно лишь то, что не удалось запустить `enb server`, причины из него не ясны.

Пока пара вопросов:
1. В качестве командной оболочки используется git bash? Если нет, стоит попробовать именно ее.
Запустится ли сервер командой `./node_modules/enb/bin/enb server`?

**Comment by voron121** [comment]
Использую GIT - bash .

Странно но попробовал удалить проект и пересоздать (пройти все пути с начала) и вроде бы все стартануло ок . Это странно ... может быть просто какой то пакет не слился или не стартовал
