### ISSUE TITLE
Переходим на сторону сервера с bem-express

### ISSUE THREAD

**Issue by godfreyd** [bem-site/bem-forum-content-ru#1420]
Привет!

Наверняка все знают про шаблонный репозиторий для динамических проектов [bem-express](https://github.com/bem/bem-express).

Если вы еще до конца не разобрались, как внутри него все устроено, то для вас мы написали tutorial: [«Переходим на сторону сервера с bem-express»](https://habrahabr.ru/company/yandex/blog/337166/).

![API bem-express](https://rawgit.com/godfreyd/bem-in-dynamic/master/static/images/chart.svg)

**Comment by Kundin** [comment]
Команды 
````git clone https://github.com/bem/bem-express.git
cd bem-express
npm i
npm run dev````

Итог
[nodemon] starting `node server`
[nodemon] child pid: 26647
[nodemon] Internal watch failed: watch /home/kndn/projects/express/server ENOSPC
[nodemon] exiting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bem-express@2.0.0 dev: `npm run make && nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-express@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kndn/.npm/_logs/2017-09-16T17_40_52_942Z-debug.log
kndn@kndn-Aspire-ES1-512 ~/projects/express $ server is listening on 3000
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/kndn/projects/express ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/kndn/projects/express/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by Kundin** [comment]
npm start - все ок. Что у меня не так?

**Comment by Kundin** [comment]
Теперь ````No command 'bem' found````
Вариант с ````export PATH=node_modules/.bin:$PATH```` не срабатывает.
Как поправить?

**Comment by Kundin** [comment]
И почему нет файла GET http://localhost:3000/livereload.js/?snipver=1

**Comment by godfreyd** [comment]
Привет. На каком шаге возникают проблемы? Прямого вызова `bem` нет.

**Comment by Kundin** [comment]
Хотелось бы как и раньше из консоли ````bem create```` делать.

**Comment by Realetive** [comment]
@Kundin а вы из корня проекта запускаете? `bem-tools` установлен локально или глобально? Потому что УМВР (устанавливал глобально).
