### ISSUE TITLE
Установка bem-express на VPS

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1428]
Помогите установить bem-express
При установке зависимостей появляется ошибка 
````
npm WARN deprecated coa@1.0.3: Please upgrade to 1.0.4 for node 0.10, 0.12, or to 2.0+ for node 4+
npm ERR! cancel after 1 retries!
npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/kndn/data/www/kn-dn.ru/.npm/_logs/2017-09-20T16_20_53_478Z-debug.log
````

Пробовал установить ````project-stub````, зависимости установились без ошибок.
Node v8.5.0

**Comment by tadatuta** [comment]
Нужно больше подробностей. Поставил начисто, не воспроизвелось:

```
/Users/tadatuta/projects/bem/bem-express nvm i 8
Downloading https://nodejs.org/dist/v8.5.0/node-v8.5.0-darwin-x64.tar.xz...
######################################################################## 100,0%
WARNING: checksums are currently disabled for node.js v4.0 and later
Now using node v8.5.0 (npm v5.3.0)
/Users/tadatuta/projects/bem/bem-express npm i

> fsevents@1.1.2 install /Users/tadatuta/projects/bem/bem-express/node_modules/fsevents
> node install

[fsevents] Success: "/Users/tadatuta/projects/bem/bem-express/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> bem-components@6.0.1 postinstall /Users/tadatuta/projects/bem/bem-express/node_modules/bem-components
> npm run drop-cache


> bem-components@6.0.1 drop-cache /Users/tadatuta/projects/bem/bem-express/node_modules/bem-components
> rm -rf .enb/tmp


> bem-express@2.0.0 postinstall /Users/tadatuta/projects/bem/bem-express
> npm run drop-cache && npm run make


> bem-express@2.0.0 drop-cache /Users/tadatuta/projects/bem/bem-express
> rm -rf .enb/tmp


> bem-express@2.0.0 make /Users/tadatuta/projects/bem/bem-express
> enb make

20:41:41.772 - build started
20:41:41.789 - [rebuild] [desktop.bundles/index/index.bemdecl.js] file-provider
20:41:41.836 - [rebuild] [desktop.bundles/index/index.levels] levels
20:41:41.871 - [rebuild] [desktop.bundles/index/index.deps.js] deps
20:41:41.875 - [rebuild] [desktop.bundles/index/index.files] files
20:41:41.875 - [rebuild] [desktop.bundles/index/index.dirs] files
20:41:42.070 - [rebuild] [desktop.bundles/index/index.tmpl.bemdecl.js] deps-by-tech-to-bemdecl
20:41:42.075 - [rebuild] [desktop.bundles/index/index.browser.js] browser-js
20:41:42.075 - [rebuild] [desktop.bundles/index/index.tmpl.deps.js] deps
20:41:42.076 - [rebuild] [desktop.bundles/index/index.tmpl.files] files
20:41:42.076 - [rebuild] [desktop.bundles/index/index.tmpl.dirs] files
20:41:42.193 - [rebuild] [desktop.bundles/index/index.css] enb-postcss
20:41:42.193 - [rebuild] [desktop.bundles/index/index.browser.bemhtml.js] bemhtml
20:41:42.204 - [rebuild] [desktop.bundles/index/index.bemtree.js] bemtree
20:41:42.207 - [rebuild] [desktop.bundles/index/index.bemhtml.js] bemhtml
20:41:42.211 - [rebuild] [desktop.bundles/index/index.js] file-merge
20:41:42.441 - [rebuild] [desktop.bundles/index/index.min.css] borschik
20:41:42.443 - [rebuild] [desktop.bundles/index/../../static/index.min.css] file-copy
20:41:42.454 - [rebuild] [desktop.bundles/index/index.min.js] borschik
20:41:42.457 - [rebuild] [desktop.bundles/index/../../static/index.min.js] file-copy
20:41:42.457 - build finished - 1433ms
npm notice created a lockfile as package-lock.json. You should commit this file.
added 943 packages in 37.864s
```

**Comment by Kundin** [comment]
А больше нет ничего, новый vps, стоит только node, git
В логах есть такая ошибка
````
11830 silly extract write-file-atomic@2.3.0
11831 verbose unlock done using /var/www/kndn/data/www/kn-dn.ru/.npm/_locks/staging-fa5ed586fb5dffa6.lock for /var/www/kndn/data/www/kn-dn.ru/bem-express/node_modules/.staging
11832 verbose type ProcessTerminatedError
11833 verbose stack ProcessTerminatedError: cancel after 1 retries!
11833 verbose stack     at Farm.<anonymous> (/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:87:25)
11833 verbose stack     at Array.forEach (<anonymous>)
11833 verbose stack     at Farm.<anonymous> (/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:81:36)
11833 verbose stack     at ontimeout (timers.js:469:11)
11833 verbose stack     at tryOnTimeout (timers.js:304:5)
11833 verbose stack     at Timer.listOnTimeout (timers.js:264:5)
11834 verbose cwd /var/www/kndn/data/www/kn-dn.ru/bem-express
11835 verbose Linux 2.6.32-042stab123.3
````

Кажется больше и нечего показать

**Comment by Kundin** [comment]
Могу дать доступ ssh, посмотрите если будет время.
Мне не срочно - просто хочу поэкспериментировать с bem-express

**Comment by Kundin** [comment]
Проблема решилась сама собой.
Переустановил ОС на сервере, выполнил все те же действия => профит.
