### ISSUE TITLE
Ошибки при сборке merged

### ISSUE THREAD

**Issue by webtehnology** [bem-site/bem-forum-content-ru#1431]
Последняя версия project-stub ругается при сборке mergred
если брать за основу https://github.com/bem/project-stub/tree/merged
те это решение не совместимо

**Comment by belozer** [comment]
@webtehnology  как ругается? Хорошо бы и конфиг сборки приложить

**Comment by webtehnology** [comment]
.enb/make.js
`const 
         fs = require('fs'),
         path = require('path'),
        techs = {
        // essential

        fileProvider: require('enb/techs/file-provider'),
        fileMerge: require('enb/techs/file-merge'),

        // optimization
        borschik: require('enb-borschik/techs/borschik'),

        // css
        postcss: require('enb-postcss/techs/enb-postcss'),
        postcssPlugins: [
            require('postcss-import')(),
            require('postcss-each'),
            require('postcss-for'),
            require('postcss-simple-vars')(),
            require('postcss-calc')(),
            require('postcss-nested'),
            require('postcss-pxtorem'),
            require('postcss-color-alpha'),
            require("postcss-custom-media"),
            require('rebem-css'),

            //require('sugarss'),
            require('postcss-url')({ url: 'rebase' }),
            require('autoprefixer')(),
            require('postcss-reporter')()
        ],

        // js
        browserJs: require('enb-js/techs/browser-js'),

        // bemtree
        // bemtree: require('enb-bemxjst/techs/bemtree'),

        // bemhtml
        bemhtml: require('enb-bemxjst/techs/bemhtml'),
        bemjsonToHtml: require('enb-bemxjst/techs/bemjson-to-html')
    },
    enbBemTechs = require('enb-bem-techs'),
    merged = require('./techs/merged'),
    levels = [
        { path: 'node_modules/bem-core/common.blocks', check: false },
        { path: 'node_modules/bem-core/desktop.blocks', check: false },
        { path: 'node_modules/bem-components/common.blocks', check: false },
        { path: 'node_modules/bem-components/desktop.blocks', check: false },
        { path: 'node_modules/bem-components/design/common.blocks', check: false },
        { path: 'node_modules/bem-components/design/desktop.blocks', check: false },
        'common.blocks',
        'desktop.blocks'
    ];

module.exports = function(config) {
    const isProd = process.env.YENV === 'production';
          mergedBundleName = 'merged',
          pathToMargedBundle = path.join('desktop.bundles', mergedBundleName);
           fs.existsSync(pathToMargedBundle) || fs.mkdirSync(pathToMargedBundle);

    merged(config, pathToMargedBundle);

    config.nodes('*.bundles/*', function(nodeConfig) {
        var isMergedNode = path.basename(nodeConfig.getPath()) === mergedBundleName;

        isMergedNode || nodeConfig.addTechs([
            [techs.fileProvider, { target: '?.bemjson.js' }],
            [enbBemTechs.bemjsonToBemdecl]
        ]);

        nodeConfig.addTechs([
            // essential
            [enbBemTechs.levels, { levels: levels }],
            [techs.fileProvider, { target: '?.bemjson.js' }],
            [enbBemTechs.bemjsonToBemdecl],
            [enbBemTechs.deps],
            [enbBemTechs.files],

            // css
            [techs.postcss, {
                target: '?.css',
                oneOfSourceSuffixes: ['post.css', 'css'],
                plugins: techs.postcssPlugins
            }],

            // bemtree
            // [techs.bemtree, { sourceSuffixes: ['bemtree', 'bemtree.js'] }],

            // bemhtml
            [techs.bemhtml, {
                sourceSuffixes: ['bemhtml', 'bemhtml.js'],
                forceBaseTemplates: true,
                engineOptions : { elemJsInstances : true }
            }],

            // html
            [techs.bemjsonToHtml],

            // client bemhtml
            [enbBemTechs.depsByTechToBemdecl, {
                target: '?.bemhtml.bemdecl.js',
                sourceTech: 'js',
                destTech: 'bemhtml'
            }],
            [enbBemTechs.deps, {
                target: '?.bemhtml.deps.js',
                bemdeclFile: '?.bemhtml.bemdecl.js'
            }],
            [enbBemTechs.files, {
                depsFile: '?.bemhtml.deps.js',
                filesTarget: '?.bemhtml.files',
                dirsTarget: '?.bemhtml.dirs'
            }],
            [techs.bemhtml, {
                target: '?.browser.bemhtml.js',
                filesTarget: '?.bemhtml.files',
                sourceSuffixes: ['bemhtml', 'bemhtml.js'],
                engineOptions : { elemJsInstances : true }
            }],

            // js
            [techs.browserJs, { includeYM: true }],
            [techs.fileMerge, {
                target: '?.js',
                sources: ['?.browser.js', '?.browser.bemhtml.js']
            }],

            // borschik
            [techs.borschik, { source: '?.js', target: '?.min.js', minify: isProd }],
            [techs.borschik, { source: '?.css', target: '?.min.css', minify: isProd }]
        ]);

        nodeConfig.addTargets([/* '?.bemtree.js', */ '?.html', '?.min.css', '?.min.js']);
        isMergedNode || nodeConfig.addTargets(['?.html']);
    });
};
`

ошибки
`03:48:52.528 - build failed
Error: Concurrent techs for target: merged.bemdecl.js, techs: "merge-bemdecl" vs "bemjson-to-bemdecl"
    at Error (native)
    at _registerTarget (/Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:415:19)
    at /Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:553:23
    at Array.forEach (native)
    at /Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:552:31
    at Array.map (native)
    at _registerTargets (/Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:551:21)
    at requireSources (/Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:496:14)
    at build (/Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/node/node.js:602:21)
    at /Users/igor/Documents/Work-frontend/webtech/node_modules/enb/lib/make.js:520:54
`

**Comment by webtehnology** [comment]
@belozer 
тут
https://github.com/webtehnology/webtechpr
