### ISSUE TITLE
Проба create-bem-react-app: баги

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1440]
Пробую сабж, после установки при попытке запуска отваливается в `node_modules/@bem/sdk.config/index.js` на `extendConfigsPathByLayer` -- что `config.levels` ожидается в виде массива (`config.levels.forEach`), тогда как на самом деле там хэш:

```javascript
{ 'src/components': { scheme: 'nested', default: true } }
```

Переделал `levels` в .bemrc` в массив:

```javascript
    "levels": [
        {
            "path": "src/components",
            "scheme": "nested",
            "default": true
        }
    ],
```

Но далее лезет ещё более странное:

```log
Error: Cannot find module 'babel-preset-es2015'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (.../node_modules/bem-react-scripts/config/webpack.config.dev.js:152:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/bem-react-scripts/scripts/start.js:31:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

М.б., стоит вытащить релиз из ветки `v0.4.*`? Похоже, что нынешнее `v1.0.0-rc*` -- вообще не стабильное?

Или где-то что-то не так сделал? (Хотя вроде только поставил по инструкции и начал пробыЮ всего-то...)

А что там по поводу `bem-react-stub` -- оно живое, кто-то пробовал? Меня смутило, что последний коммит -- аж год назад.

Хелп, что ли?

**UPD:** (При просмотре сообщения на форуме выскакивает странный квотинг для *markdown-code*.)

**Comment by awinogradov** [comment]
Кажется, тут имеется в виду create-bem-react-app, а не bem-react-core.

**Comment by awinogradov** [comment]
@lilliputten пернеси ишью по адресу, плиз – мы все починим

**Comment by lilliputten** [comment]
@awinogradov Да, именно `create-bem-react-app`.

(Кстати, вспомнил, что было шоу от @veged по адаптации redux-react-todomvc для работы с bem-react-core. Попробую ещё оттуда зайти. Кодов нет, но есть запечатлённый на видео процесс и кусочек подготовленных конфигов у него в акаунте.)

***UPD*** Посмотрел на версии. Из npm ставится 0.0.3:
```shell
$ npm view create-bem-react-app version
0.0.3

$ npm -v
3.10.10

$ node -v
v6.10.0
```
М.б., стоит вытащить что-то посвежее?

**Comment by veged** [comment]
@lilliputten в каком смысле «посвежее»? там ставится что-то отличное от https://github.com/bem/create-bem-react-app ?
