### ISSUE TITLE
Express 4 - ошибка при multipart/form-data

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1480]
Немного не по теме, наверное..
Кто-то знает как в Express 4 включить поддержку форм с `multipart/form-data`?
Уже использовал и `formidable`, и `multer`, но все равно стабильно получаю ответ:

`
InvalidContentTypeError: Could not parse content type header: multipart/form-data; boundary=----WebKitFormBoundaryE8eRwjA5gxuFzaTp
    at createError (/home/kndn/projects/bets/node_modules/error/typed.js:31:22)
    at anyBody (/home/kndn/projects/bets/node_modules/body/any.js:36:18)
    at Server.handler (/home/kndn/projects/bets/node_modules/tiny-lr/src/server.js:145:32)
    at tinylr (/home/kndn/projects/bets/node_modules/tiny-lr/src/index.js:45:9)
    at Layer.handle [as handle_request] (/home/kndn/projects/bets/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kndn/projects/bets/node_modules/express/lib/router/index.js:317:13)
    at /home/kndn/projects/bets/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kndn/projects/bets/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kndn/projects/bets/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/kndn/projects/bets/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at SessionStrategy.authenticate (/home/kndn/projects/bets/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (/home/kndn/projects/bets/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/kndn/projects/bets/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/kndn/projects/bets/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kndn/projects/bets/node_modules/express/lib/router/index.js:317:13)
    at /home/kndn/projects/bets/node_modules/express/lib/router/index.js:284:7
`

Куда копать? Что не так? С какого конкретно момента это происходит понять не могу..

**Comment by Kundin** [comment]
Пару дней потратил на это.
Проблема решена, передал app напрямую, вместо использования express.Router и  вуаля..

**Comment by Realetive** [comment]
Та же фигня возникла. Скорее всего дело в liveReload-плагине `tiny-lr`, который перехватывает POST-запрос и пытается просунуть в него свой скрипт.
