### ISSUE TITLE
При сборке проекта на БЭМ возникает ошибка TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by fregire** [bem-site/bem-forum-content-ru#1552]
Следую инструкциям описанным в этой статье - https://habr.com/company/yandex/blog/251473/ 
При сборке и старте проекта(npm start или enb server) возникает ошибка в borshik'е 
При этом проект собирает все, но при изменении чего-либо в файлах не реагирует и не перезагружает страницу.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:651:5)
    at res.__constructor (C:\Users\Admin\Desktop\currebt\secondproject\node_modules\borschik\lib\tech.js:87:47)
    at new res (C:\Users\Admin\Desktop\currebt\secondproject\node_modules\borschik\node_modules\inherit\lib\inherit.js:123:43)
    at res.createFile (C:\Users\Admin\Desktop\currebt\secondproject\node_modules\borschik\lib\tech.js:24:24)
```
![Скриншот](https://i.ibb.co/xhMhC2n/Screenshot-230.png)

**Comment by wannabenormal** [comment]
Столкнулся точно с такой же проблемой, возможно нашлось какое-то решение? Использую тот же bem-stub из поста на хабре

**Comment by Realetive** [comment]
@fregire , @Pesthedog а можете репозиторий сюда выгрузить? Так будет проще разобраться.
